apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: python-lambda-operator
  namespace: python-lambda-operator
spec:
  generateSelector: true
  parentResource:
    apiVersion: example.com/v1
    resource: pythonlambdas
  childResources:
  - apiVersion: v1
    resource: configmaps
    updateStrategy:
      method: Recreate
  - apiVersion: v1
    resource: services
    updateStrategy:
      method: Recreate
  - apiVersion: networking.k8s.io/v1beta1
    resource: ingresses
    updateStrategy:
      method: InPlace
  - apiVersion: v1
    resource: pods
    updateStrategy:
      method: Recreate
  hooks:
    sync:
      webhook:
        url: http://webhook-python-lambda-operator.python-lambda-operator/sync
