apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-python-lambda-operator
  namespace: python-lambda-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook-python-lambda-operator
  template:
    metadata:
      labels:
        app: webhook-python-lambda-operator
    spec:
      containers:
      - name: controller
        image: python:2.7
        command: ["python", "/hooks/sync.py"]
        volumeMounts:
        - name: hooks
          mountPath: /hooks
      volumes:
      - name: hooks
        configMap:
          name: webhook-python-lambda-operator
